[package]
name = "crit"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }
borsh = { version = "1.5.7", features = ["derive"] }
